### ISSUE TITLE
error with aai industry and space exploration

### ISSUE THREAD

**Issue by thefinalguard** [pfgithub/liquid-science#6]
when using this mod in conjunction with the space exploration mod or aai industry mod, you can not build the machine that produces the science because you need to research logistics 1 in order to unlock yellow belts.

**Comment by pfgithub** [comment]
I might just make it so red science is the normal recipe to prevent conflicts like this

**Comment by pfgithub** [comment]
Version 0.1.10 disables liquid science for red science which should fix this.

**Comment by thefinalguard** [comment]
Better yet, make the machine that makes the science not require belt in
it's crafting cost. It seems a little expensive considering you need it to
create science of any sort.

**Comment by pfgithub** [comment]
In vanilla, belt is very cheap. Do you have any suggestions for a better recipe? The current one was pretty randomly chosen so I'm fine with changing it.

**Comment by thefinalguard** [comment]
True, belt is cheap in vanilla, but removing the belt from the recipe
entirely would be the way I'd go. (Considering the aai industry has yellow
belt locked behind red research) It already costs like five different items
to craft currently... It could be difficult to produce early game. (I don't
know what Bob's mods do to the science tree cuz I haven't played with them
too much.) I do want to say that your mod seems super interesting. Being
able to store just a back-up of liquid science in fluid tanks seems super
nice to me.
